import os, sys

def django_setup():
    # Setup environ
    sys.path.append(os.getcwd())
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "braid.settings")

    # Setup django
    import django
    django.setup()

django_setup()

from experiments.models import Author

def clean_db():
    Author.objects.all().delete()


def create_authors(first_names):
    return [Author.objects.create(firstName=first) for first in first_names]


def create_data():
    author_names = ['Camilleri', 'Franco', 'Pettygrove', 'Luke']
    (camilleri, franco, pettygrove, luke) = create_authors(author_names)


def view():
    print(Author.objects.all())


if __name__ == '__main__':
    clean_db()
    create_data()
    view()

# #########################################
# ##########################################
# camilleridataset = Experiments(experimentName = 'CamilleriDataSet', conditions = None, authorID = camilleri)
# camilleridataset.save()
# francodataset = Experiments(experimentName = 'FrancoDataSet', conditions = None, authorID = franco)
# francodataset.save()
# pettygrovedataset = Experiments(experimentName = 'PettygroveDataSet', conditions = None, authorID = pettygrove)
# pettygrovedataset.save()
# lukedataset = Experiments(experimentName = 'LukeDatasets', conditions = None, authorID = luke)
# lukedataset.save()
# #############################################
# #############################################
# file1 = Files(experimentID = camilleridataset, path = "data/ImageData/CamilleriDataSet/co-culture-confocal-T600-LC", mimetype = 'Image', mimetype_type = 'tif')
# file1.save()
# file2 = Files(experimentID = camilleridataset, path = "data/ImageData/CamilleriDataSet/example co-culture biofilm-LC", mimetype = 'Text', mimetype_type = 'xlsx')
# file2.save()
# ########################################
# ###################################
# file3 = Files(experimentID = francodataset, path = "data/ImageData/FrancoDataSet/EAL-10230x", mimetype = 'Image', mimetype_type = 'png')
# file3.save()
# file4 = Files(experimentID = francodataset, path = "data/ImageData/FrancoDataSet/EAL-23000x", mimetype = 'Image', mimetype_type = 'png')
# file4.save()
# file5 = Files(experimentID = francodataset, path = "data/ImageData/FrancoDataSet/EDL-1430x", mimetype = 'Image', mimetype_type = 'png')
# file5.save()
# file6 = Files(experimentID = francodataset, path = "data/ImageData/FrancoDataSet/EDL-17700x", mimetype = 'Image', mimetype_type = 'png')
# file6.save()
# #########################################
# ##############################################
# file7 = Files(experimentID = pettygrovedataset, path = "data/ImageData/PettygroveDataSet/11-16-2017/CFU Counts 11-16", mimetype = 'Text', mimetype_type = 'xlsx')
# file7.save()
# file8 = Files(experimentID = pettygrovedataset, path = "data/ImageData/PettygroveDataSet/11-16-2017/Experiment", mimetype = 'Text', mimetype_type = 'lif')
# file8.save()
# file9 = Files(experimentID = pettygrovedataset, path = "data/ImageData/PettygroveDataSet/11-16-2017/Growth Data 11-16 v2", mimetype = 'Text', mimetype_type = 'xlsx')
# file9.save()
# file10 = Files(experimentID = pettygrovedataset, path = "data/ImageData/PettygroveDataSet/11-16-2017/Growth Data 11-16", mimetype = 'Text', mimetype_type = 'xlsx')
# file10.save()
# file11 = Files(experimentID = pettygrovedataset, path = "data/ImageData/PettygroveDataSet/11-16-2017/Patrol Data 11-16", mimetype = 'Text', mimetype_type = 'xlsx')
# file11.save()
# file12 = Files(experimentID = pettygrovedataset, path = "data/ImageData/PettygroveDataSet/11-16-2017/Pos 1", mimetype = 'Video', mimetype_type = 'avi')
# file12.save()
# file13 = Files(experimentID = pettygrovedataset, path = "data/ImageData/PettygroveDataSet/11-16-2017/Pos 2", mimetype = 'Video', mimetype_type = 'avi')
# file13.save()
# file14 = Files(experimentID = pettygrovedataset, path = "data/ImageData/PettygroveDataSet/11-16-2017/Pos 3", mimetype = 'Video', mimetype_type = 'avi')
# file14.save()
# file15 = Files(experimentID = pettygrovedataset, path = "data/ImageData/PettygroveDataSet/11-16-2017/Pos 4", mimetype = 'Video', mimetype_type = 'avi')
# file15.save()
# file16 = Files(experimentID = pettygrovedataset, path = "data/ImageData/PettygroveDataSet/11-16-2017/Pos 5", mimetype = 'Video', mimetype_type = 'avi')
# file16.save()
# file17 = Files(experimentID = pettygrovedataset, path = "data/ImageData/PettygroveDataSet/11-16-2017/Pos 5", mimetype = 'Text', mimetype_type = 'xls')
# file17.save()
# file18 = Files(experimentID = pettygrovedataset, path = "data/ImageData/PettygroveDataSet/11-16-2017/Pos 6", mimetype = 'Video', mimetype_type = 'avi')
# file18.save()
# file19 = Files(experimentID = pettygrovedataset, path = "data/ImageData/PettygroveDataSet/11-16-2017/Pos 6", mimetype = 'Text', mimetype_type = 'xls')
# file19.save()
# file20 = Files(experimentID = pettygrovedataset, path = "data/ImageData/PettygroveDataSet/11-16-2017/Pos 7", mimetype = 'Video', mimetype_type = 'avi')
# file20.save()
# file21 = Files(experimentID = pettygrovedataset, path = "data/ImageData/PettygroveDataSet/11-16-2017/Pos 7", mimetype = 'Text', mimetype_type = 'xls')
# file21.save()
# file22 = Files(experimentID = pettygrovedataset, path = "data/ImageData/PettygroveDataSet/11-16-2017/Pos 8 Gray", mimetype = 'Video', mimetype_type = 'avi')
# file22.save()
# file23 = Files(experimentID = pettygrovedataset, path = "data/ImageData/PettygroveDataSet/11-16-2017/Pos 8", mimetype = 'Video', mimetype_type = 'avi')
# file23.save()
# file24 = Files(experimentID = pettygrovedataset, path = "data/ImageData/PettygroveDataSet/11-16-2017/Pos 8", mimetype = 'Text', mimetype_type = 'xls')
# file24.save()
# file25 = Files(experimentID = pettygrovedataset, path = "data/ImageData/PettygroveDataSet/11-16-2017/Speed Data 11-16-2017", mimetype = 'Text', mimetype_type = 'xlsx')
# file25.save()
#
# ######################################################
# file26 = Files(experimentID = pettygrovedataset, path = "data/ImageData/PettygroveDataSet/11-28-2017/CFU Counts 11-28", mimetype = 'Text', mimetype_type = 'xlsx')
# file26.save()
# file27 = Files(experimentID = pettygrovedataset, path = "data/ImageData/PettygroveDataSet/11-28-2017/Experiment", mimetype = 'Text', mimetype_type = 'lif')
# file27.save()
# file28 = Files(experimentID = pettygrovedataset, path = "data/ImageData/PettygroveDataSet/11-28-2017/Growth Data 11-28", mimetype = 'Text', mimetype_type = 'xlsx')
# file28.save()
# file30 = Files(experimentID = pettygrovedataset, path = "data/ImageData/PettygroveDataSet/11-28-2017/Patrol Data 11-28", mimetype = 'Text', mimetype_type = 'xlsx')
# file30.save()
# file31 = Files(experimentID = pettygrovedataset, path = "data/ImageData/PettygroveDataSet/11-28-2017/Pos 1", mimetype = 'Video', mimetype_type = 'avi')
# file31.save()
# file32 = Files(experimentID = pettygrovedataset, path = "data/ImageData/PettygroveDataSet/11-28-2017/Pos 2", mimetype = 'Video', mimetype_type = 'avi')
# file32.save()
# file33 = Files(experimentID = pettygrovedataset, path = "data/ImageData/PettygroveDataSet/11-28-2017/Pos 3", mimetype = 'Video', mimetype_type = 'avi')
# file33.save()
# file34 = Files(experimentID = pettygrovedataset, path = "data/ImageData/PettygroveDataSet/11-28-2017/Pos 4", mimetype = 'Video', mimetype_type = 'avi')
# file34.save()
# file35 = Files(experimentID = pettygrovedataset, path = "data/ImageData/PettygroveDataSet/11-28-2017/Pos 5", mimetype = 'Video', mimetype_type = 'avi')
# file35.save()
# file35a = Files(experimentID = pettygrovedataset, path = "data/ImageData/PettygroveDataSet/11-28-2017/Pos 5 Gray", mimetype = 'Video', mimetype_type = 'avi')
# file35a.save()
# file36 = Files(experimentID = pettygrovedataset, path = "data/ImageData/PettygroveDataSet/11-28-2017/Pos 5", mimetype = 'Text', mimetype_type = 'xls')
# file36.save()
# file37 = Files(experimentID = pettygrovedataset, path = "data/ImageData/PettygroveDataSet/11-28-2017/Pos 6", mimetype = 'Video', mimetype_type = 'avi')
# file37.save()
# file35ab = Files(experimentID = pettygrovedataset, path = "data/ImageData/PettygroveDataSet/11-28-2017/Pos 6 Gray", mimetype = 'Video', mimetype_type = 'avi')
# file35ab.save()
# file38 = Files(experimentID = pettygrovedataset, path = "data/ImageData/PettygroveDataSet/11-28-2017/Pos 6", mimetype = 'Text', mimetype_type = 'xls')
# file38.save()
# file39 = Files(experimentID = pettygrovedataset, path = "data/ImageData/PettygroveDataSet/11-28-2017/Pos 7", mimetype = 'Video', mimetype_type = 'avi')
# file39.save()
# file40 = Files(experimentID = pettygrovedataset, path = "data/ImageData/PettygroveDataSet/11-28-2017/Pos 7", mimetype = 'Text', mimetype_type = 'xls')
# file40.save()
# file35abc = Files(experimentID = pettygrovedataset, path = "data/ImageData/PettygroveDataSet/11-28-2017/Pos 7 Gray", mimetype = 'Video', mimetype_type = 'avi')
# file35abc.save()
# file41 = Files(experimentID = pettygrovedataset, path = "data/ImageData/PettygroveDataSet/11-28-2017/Pos 8 Gray", mimetype = 'Video', mimetype_type = 'avi')
# file41.save()
# file42 = Files(experimentID = pettygrovedataset, path = "data/ImageData/PettygroveDataSet/11-28-2017/Pos 8", mimetype = 'Video', mimetype_type = 'avi')
# file42.save()
# file43 = Files(experimentID = pettygrovedataset, path = "data/ImageData/PettygroveDataSet/11-28-2017/Pos 8", mimetype = 'Text', mimetype_type = 'xls')
# file43.save()
# file44 = Files(experimentID = pettygrovedataset, path = "data/ImageData/PettygroveDataSet/11-28-2017/Speed Data 11-28-2017", mimetype = 'Text', mimetype_type = 'xlsx')
# file44.save()
#
# #################################################################
# file45 = Files(experimentID = pettygrovedataset, path = "data/ImageData/PettygroveDataSet/12-5-2017/CFU Counts 12-5", mimetype = 'Text', mimetype_type = 'xlsx')
# file45.save()
# file46 = Files(experimentID = pettygrovedataset, path = "data/ImageData/PettygroveDataSet/12-5-2017/Experiment", mimetype = 'Text', mimetype_type = 'lif')
# file46.save()
# file47 = Files(experimentID = pettygrovedataset, path = "data/ImageData/PettygroveDataSet/12-5-2017/Growth Data 12-5-2017", mimetype = 'Text', mimetype_type = 'xlsx')
# file47.save()
# file48 = Files(experimentID = pettygrovedataset, path = "data/ImageData/PettygroveDataSet/12-5-2017/Patrol Data 12-5-2017", mimetype = 'Text', mimetype_type = 'xlsx')
# file48.save()
# file49 = Files(experimentID = pettygrovedataset, path = "data/ImageData/PettygroveDataSet/12-5-2017/Pos 1", mimetype = 'Video', mimetype_type = 'avi')
# file49.save()
# file50 = Files(experimentID = pettygrovedataset, path = "data/ImageData/PettygroveDataSet/12-5-2017/Pos 2", mimetype = 'Video', mimetype_type = 'avi')
# file50.save()
# file51 = Files(experimentID = pettygrovedataset, path = "data/ImageData/PettygroveDataSet/12-5-2017/Pos 3", mimetype = 'Video', mimetype_type = 'avi')
# file51.save()
# file52 = Files(experimentID = pettygrovedataset, path = "data/ImageData/PettygroveDataSet/12-5-2017/Pos 4", mimetype = 'Video', mimetype_type = 'avi')
# file52.save()
# file53 = Files(experimentID = pettygrovedataset, path = "data/ImageData/PettygroveDataSet/12-5-2017/Pos 5", mimetype = 'Video', mimetype_type = 'avi')
# file53.save()
# file54 = Files(experimentID = pettygrovedataset, path = "data/ImageData/PettygroveDataSet/12-5-2017/Pos 5 Gray", mimetype = 'Video', mimetype_type = 'avi')
# file54.save()
# file55 = Files(experimentID = pettygrovedataset, path = "data/ImageData/PettygroveDataSet/12-5-2017/Pos 5 Green", mimetype = 'Video', mimetype_type = 'avi')
# file55.save()
# file56 = Files(experimentID = pettygrovedataset, path = "data/ImageData/PettygroveDataSet/12-5-2017/Pos 6", mimetype = 'Video', mimetype_type = 'avi')
# file56.save()
# file57 = Files(experimentID = pettygrovedataset, path = "data/ImageData/PettygroveDataSet/12-5-2017/Pos 6 Gray", mimetype = 'Video', mimetype_type = 'avi')
# file57.save()
# file58 = Files(experimentID = pettygrovedataset, path = "data/ImageData/PettygroveDataSet/12-5-2017/Pos 6 Green", mimetype = 'Video', mimetype_type = 'avi')
# file58.save()
# file59 = Files(experimentID = pettygrovedataset, path = "data/ImageData/PettygroveDataSet/12-5-2017/Pos 7", mimetype = 'Video', mimetype_type = 'avi')
# file59.save()
# file60 = Files(experimentID = pettygrovedataset, path = "data/ImageData/PettygroveDataSet/12-5-2017/Pos 7 Gray", mimetype = 'Video', mimetype_type = 'avi')
# file60.save()
# file61 = Files(experimentID = pettygrovedataset, path = "data/ImageData/PettygroveDataSet/12-5-2017/Pos 7 Green", mimetype = 'Video', mimetype_type = 'avi')
# file61.save()
# file62 = Files(experimentID = pettygrovedataset, path = "data/ImageData/PettygroveDataSet/12-5-2017/Pos 8", mimetype = 'Video', mimetype_type = 'avi')
# file62.save()
# file63 = Files(experimentID = pettygrovedataset, path = "data/ImageData/PettygroveDataSet/12-5-2017/Pos 8 Gray", mimetype = 'Video', mimetype_type = 'avi')
# file63.save()
# file64 = Files(experimentID = pettygrovedataset, path = "data/ImageData/PettygroveDataSet/12-5-2017/Pos 8 Green", mimetype = 'Video', mimetype_type = 'avi')
# file64.save()
# file65 = Files(experimentID = pettygrovedataset, path = "data/ImageData/PettygroveDataSet/11-28-2017/Pos 5", mimetype = 'Text', mimetype_type = 'xls')
# file65.save()
# file66 = Files(experimentID = pettygrovedataset, path = "data/ImageData/PettygroveDataSet/11-28-2017/Pos 6", mimetype = 'Text', mimetype_type = 'xls')
# file66.save()
# file67 = Files(experimentID = pettygrovedataset, path = "data/ImageData/PettygroveDataSet/11-28-2017/Pos 7", mimetype = 'Text', mimetype_type = 'xls')
# file67.save()
# file68 = Files(experimentID = pettygrovedataset, path = "data/ImageData/PettygroveDataSet/11-28-2017/Pos 8", mimetype = 'Text', mimetype_type = 'xls')
# file68.save()
# file69 = Files(experimentID = pettygrovedataset, path = "data/ImageData/PettygroveDataSet/11-28-2017/Speed Data 12-5-2017", mimetype = 'Text', mimetype_type = 'xlsx')
# file69.save()
# file70 = Files(experimentID = pettygrovedataset, path = "data/ImageData/PettygroveDataSet/11-28-2017/Tile Data 12-5-2017", mimetype = 'Text', mimetype_type = 'xlsx')
# file70.save()
#
# ##################################################################
#
# file71 = Files(experimentID = lukedataset, path = "data/OmicsData/LukeDataset/LargeMetagenome/PKF9-QUALITY_PASSED_R1", mimetype = 'Text', mimetype_type = 'fastq')
# file71.save()
# file71 = Files(experimentID = lukedataset, path = "data/OmicsData/LukeDataset/LargeMetagenome/PKF9-QUALITY_PASSED_R2", mimetype = 'Text', mimetype_type = 'fastq')
# file71.save()
# file71 = Files(experimentID = lukedataset, path = "data/OmicsData/LukeDataset/LargeMetagenome/PKF9-QUALITY_PASSED_R2.fastq", mimetype = 'unknown', mimetype_type = 'zip')
# file71.save()
# file71 = Files(experimentID = lukedataset, path = "data/OmicsData/LukeDataset/LargeMetagenome/PKF9-READ_IDs.cPickle", mimetype = 'Text', mimetype_type = 'z')
# file71.save()
# file71 = Files(experimentID = lukedataset, path = "data/OmicsData/LukeDataset/LargeMetagenome/PKF9-STATS", mimetype = 'Text', mimetype_type = 'txt')
# file71.save()
# file71 = Files(experimentID = lukedataset, path = "data/OmicsData/LukeDataset/LargeMetagenome/ziSWHTdA", mimetype = 'unknown', mimetype_type = 'unknown')
# file71.save()
# ###########################################
# file71 = Files(experimentID = lukedataset, path = "data/OmicsData/LukeDataset/SEMImages/LM_Culture_2_2017_a", mimetype = 'Image', mimetype_type = 'tif')
# file71.save()
# file71 = Files(experimentID = lukedataset, path = "data/OmicsData/LukeDataset/SEMImages/LM_Culture_2_2017_b", mimetype = 'Image', mimetype_type = 'tif')
# file71.save()
# file71 = Files(experimentID = lukedataset, path = "data/OmicsData/LukeDataset/SEMImages/LM_Culture_2_2017_c", mimetype = 'Image', mimetype_type = 'tif')
# file71.save()
# file71 = Files(experimentID = lukedataset, path = "data/OmicsData/LukeDataset/SEMImages/LM_Culture_2_2017_d", mimetype = 'Image', mimetype_type = 'tif')
# file71.save()
# file71 = Files(experimentID = lukedataset, path = "data/OmicsData/LukeDataset/SEMImages/LM_Culture_2_2017_e", mimetype = 'Image', mimetype_type = 'tif')
# file71.save()
# file71 = Files(experimentID = lukedataset, path = "data/OmicsData/LukeDataset/SEMImages/LM_Culture_2_2017_f", mimetype = 'Image', mimetype_type = 'tif')
# file71.save()
# file71 = Files(experimentID = lukedataset, path = "data/OmicsData/LukeDataset/SEMImages/LM_Culture_2_2017_g", mimetype = 'Image', mimetype_type = 'tif')
# file71.save()
# file71 = Files(experimentID = lukedataset, path = "data/OmicsData/LukeDataset/SEMImages/LM_Culture_2_2017_h", mimetype = 'Image', mimetype_type = 'tif')
# file71.save()
# file71 = Files(experimentID = lukedataset, path = "data/OmicsData/LukeDataset/SEMImages/LM_Culture_2_2017_i", mimetype = 'Image', mimetype_type = 'tif')
# file71.save()
# file71 = Files(experimentID = lukedataset, path = "data/OmicsData/LukeDataset/SEMImages/LM_Culture_2_2017_j", mimetype = 'Image', mimetype_type = 'tif')
# file71.save()
# file71 = Files(experimentID = lukedataset, path = "data/OmicsData/LukeDataset/SEMImages/LM_Culture_2_2017_k", mimetype = 'Image', mimetype_type = 'tif')
# file71.save()
# file71 = Files(experimentID = lukedataset, path = "data/OmicsData/LukeDataset/SEMImages/LM_Culture_2_2017_l", mimetype = 'Image', mimetype_type = 'tif')
# file71.save()
# file71 = Files(experimentID = lukedataset, path = "data/OmicsData/LukeDataset/SEMImages/LM_Culture_2_2017_m", mimetype = 'Image', mimetype_type = 'tif')
# file71.save()
# file71 = Files(experimentID = lukedataset, path = "data/OmicsData/LukeDataset/SEMImages/LM_Culture_2_2017_n", mimetype = 'Image', mimetype_type = 'tif')
# file71.save()
# ################################################
# file71 = Files(experimentID = lukedataset, path = "data/OmicsData/LukeDataset/SmallMetagenome/13_S1_L001_R1_001", mimetype = 'Text', mimetype_type = 'fastq')
# file71.save()
# file71 = Files(experimentID = lukedataset, path = "data/OmicsData/LukeDataset/SmallMetagenome/13_S1_L001_R2_001", mimetype = 'Text', mimetype_type = 'fastq')
# file71.save()
# file71 = Files(experimentID = lukedataset, path = "data/OmicsData/LukeDataset/SmallMetagenome/13_S1_L001_R1_001.fastq", mimetype = 'unknown', mimetype_type = 'gz')
# file71.save()
# file71 = Files(experimentID = lukedataset, path = "data/OmicsData/LukeDataset/SmallMetagenome/13_S1_L001_R2_001.fastq", mimetype = 'unknown', mimetype_type = 'gz')
# file71.save()
# file71 = Files(experimentID = lukedataset, path = "data/OmicsData/LukeDataset/SmallMetagenome/Csubt_wholegenome", mimetype = 'unknown', mimetype_type = 'unknown')
# file71.save()
# file71 = Files(experimentID = lukedataset, path = "data/OmicsData/LukeDataset/SmallMetagenome/Mthermo_wholegenome", mimetype = 'unknown', mimetype_type = 'unknown')
# file71.save()
# file71 = Files(experimentID = lukedataset, path = "data/OmicsData/LukeDataset/SmallMetagenome/R1_pe", mimetype = 'unknown', mimetype_type = 'unknown')
# file71.save()
# file71 = Files(experimentID = lukedataset, path = "data/OmicsData/LukeDataset/SmallMetagenome/R1_se", mimetype = 'unknown', mimetype_type = 'unknown')
# file71.save()
# file71 = Files(experimentID = lukedataset, path = "data/OmicsData/LukeDataset/SmallMetagenome/R2_pe", mimetype = 'unknown', mimetype_type = 'unknown')
# file71.save()
# file71 = Files(experimentID = lukedataset, path = "data/OmicsData/LukeDataset/SmallMetagenome/R1_se", mimetype = 'unknown', mimetype_type = 'unknown')
# file71.save()
#
# ###########################################################
# fileA = Files.objects.get(pk = 61)
# fileB = Files.objects.get(pk = 62)
# file1 = textFeatures(numberOfA = 837918, numberOfC = 505786, numberOfG = 504663 , numberOfT = 841082, textFileID = fileA)
# file1.save()
# file2 = textFeatures(numberOfA = 439339, numberOfC = 433130 , numberOfG = 434571, numberOfT = 444338, textFileID = fileB)
# file2.save()
#
# #done on LukeDataSet smallmetagenome
# #####################################################################
# fileA = Files.objects.get(pk = 9)
# fileB = Files.objects.get(pk = 10)
# fileC = Files.objects.get(pk = 11)
# fileD = Files.objects.get(pk = 12)
# file2 = imageFeatures(uptoFifty = 202303 , fiftyToHundred = 104534, hundredToOneFifty = 44775 , oneFiftyToTwoHundred=23009, twoHundredToTwoFiftyFive = 9871, imageFileID = fileA)
# file2.save()
# file3 = imageFeatures(uptoFifty = 257836, fiftyToHundred =  54207, hundredToOneFifty =  27406 , oneFiftyToTwoHundred = 17229, twoHundredToTwoFiftyFive =  10867, imageFileID = fileB)
# file3.save()
# file4 = imageFeatures(uptoFifty = 121029 , fiftyToHundred = 199729, hundredToOneFifty =  58192, oneFiftyToTwoHundred =  5234, twoHundredToTwoFiftyFive= 308, imageFileID = fileC)
# file4.save()
# file5 = imageFeatures(uptoFifty = 177237, fiftyToHundred = 95153 , hundredToOneFifty = 65569 , oneFiftyToTwoHundred = 27916, twoHundredToTwoFiftyFive =  3044, imageFileID = fileD)
# file5.save()
# #done on FrancoDataSet
